apiVersion: apps/v1 # apiVersion 명세
kind: Deployment # 구성 파일이 Deployment 객체임을 명시
metadata:
  name: second-app-deployment # Deployment 객체 이름 설정
  labels: 
    - group: example
spec:
  replicas: 1 # 파드의 레플리카 셋 몇 개할지 설정
  selector:
    # matchLabels:
    #   app: second-app # 라벨(k:v)이 맞는 파드들을 이 Deployment 객체가 책임지겠다를 명시 
    matchExpressions:
      - {key: app, operator: In, values: [second-app, first-app]} # label key가 app 이고, values 범위안에 들어가는 pod를 select 해라
      # operator에는 In, NotIn, Exists, DoNotExist가 있다.
  template: # 파드의 템플릿은 어떻게 할 것인가?
    metadata:
      labels:
        app: second-app # 라벨 설정
    spec: # 파드의 스펙
      containers: # 지금은 컨테이너 하나만
        - name: second-node # 컨테이너 이름
          image: juniper0917/kub-first-app:2 # 컨테이너 베이스 이미지


# kubectl apply -f=deployment.yaml 
# 위 명령어로 해당 구성 적용 가능

# kubectl delete -f=deployment.yaml
# 위 명령어로 쿠버네티스 클러스터에서 구성 제거 가능

# kubectl delete -l group=example
# 위 명령어로 label로 클러스터에서 구성 제거 가능