apiVersion: v1 # Service는 기본적으로 apiVersion이 core/v1임. 따라서 core 생략가능
kind: Service # 해당 config 파일은 Service 구성 파일임을 명시
metadata:
  name: backend # Service 이름 설정
spec:
  selector:
    app: second-app # 파드의 label과 일치되는 파드들을 관리할 것임을 명시
  ports: # 어떤식으로 Deployment를 외부 세계에 노출할지 명세
    - protocol: 'TCP' # 프로토콜은 TCP
      port: 80 # 외부 포트는 80
      targetPort: 8080 # 파드 내부 포트는 8080
  type: LoadBalancer # 로드밸런서 타입으로 노출